spring:
  datasource:
    password: root
    username: root
    url: jdbc:sqlite:src/main/resources/db/boot-blog.db
    driver-class-name: org.sqlite.JDBC
    schema: classpath:db/schema.sql

mapper:
  indentity: sqlite3

# pagehelper
pagehelper:
  helperDailect: sqlite3